# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.1
loader_version=0.18.6
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.1.0
maven_group=net.the_blue_shark.peculiar_creatures
archives_base_name=peculiar_creatures

# Dependencies
fabric_api_version=0.145.4+26.1.1
# https://polymer.pb4.eu/latest/polymer-core/getting-started/
polymer_version=0.16.1+26.1.1
server_translations_api_version=3.0.1+26.1
bil_version=2.0.5+26.1
