# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.2
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=1.0.1
maven_group=net.the_blue_shark.peculiar_creatures
archives_base_name=peculiar_creatures

# Dependencies
fabric_version=0.139.5+1.21.11
# https://polymer.pb4.eu/latest/polymer-core/getting-started/
polymer_version=0.15.0-beta.4+1.21.11-rc2
server_translations_api_version=2.5.2+1.21.9-pre3
bil_version=1.2.7+1.21