# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.1.0
maven_group=net.the_blue_shark.peculiar_creatures
archives_base_name=peculiar_creatures

# Dependencies
fabric_api_version=0.153.0+26.2
# https://polymer.pb4.eu/latest/polymer-core/getting-started/
polymer_version=0.17.1+26.2
server_translations_api_version=3.1.0+26.2
notica_version=2.1.0+26.2

# bil_version= check curse maven ...
molang_compiler_version=3.1.1.19

